<img src="Bumblebee-Anatomy-800px.jpg" height="400" width="100%">
<p>This is basically a about page for <b>Bumblebees</b>. I will give a few facts on <b>Bumblebees</b></p>
<ul>
  <li>Bumblebee eggs are shaped like sausages.</li>
  <li>Queen bees control the genetics of their offspring.</li>
  <li>Bees have complicated family trees.</li>
  <li>Bumblebees air condition their nests with their own wings.</li>
  <li>Bumblebees don’t die when they sting</li>
</ul>

