<img src="Bumblebee-Anatomy-800px.jpg" height="400" width="100%">
<p>This is basically a about page for <b>Bumblebees</b>. I will give a few facts on <b>Bumblebees.</b> Some of these you may know. However, maybe you will learn something new.</p>
<ul>
  <li>Bumblebee eggs are shaped like sausages.</li>
  <li><b>Queen bees control the genetics of their offspring.</li>
  <li>Bees have complicated family trees.</li>
  <li>Bumblebees air condition their nests with their own wings.</li>
  <li>Bumblebees don’t die when they sting.</b></li>
</ul>

